# Generated by Django 4.2.11 on 2024-05-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
