# Generated by Django 4.2.11 on 2024-05-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_content_topic_alter_question_topic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='three_d_file',
            field=models.FileField(blank=True, null=True, upload_to='content_3d', verbose_name='3D File'),
        ),
    ]
