# Generated by Django 4.2.11 on 2024-05-18 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_content_three_d_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTestProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Is completed')),
                ('start_date', models.DateTimeField(auto_now_add=True, verbose_name='Start date')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='End date')),
                ('correct_answers', models.IntegerField(default=0, verbose_name='Correct answers')),
                ('gained_points', models.IntegerField(default=0, verbose_name='Gained points')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_progress', to='main.topic', verbose_name='Topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_progress', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User test progress',
                'verbose_name_plural': 'User test progresses',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserQuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is correct')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='main.questionanswer', verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='main.question', verbose_name='Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_answers', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User question answer',
                'verbose_name_plural': 'User question answers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='usertestprogress',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_user_topic_test_progress'),
        ),
        migrations.AddConstraint(
            model_name='userquestionanswer',
            constraint=models.UniqueConstraint(fields=('user', 'question'), name='unique_user_question_answer'),
        ),
    ]
